### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by Lpker-2006** [TheDevFromKer/RDP-Brute#4]
Python verision is 3.7.0
 i start to run start.py in Windows10 then .
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\RDP-test\RDP-Brute\start.py", line 81, in <module>
    loop.run_until_complete(start())
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\Desktop\RDP-test\RDP-Brute\start.py", line 62, in start
    for rez in await asyncio.gather(*tasks):
  File "C:\Users\Administrator\Desktop\RDP-test\RDP-Brute\start.py", line 22, in connect
    a = await run(r_agr, limit=0, stdout=DEVNULL, stderr=DEVNULL)
  File "C:\Program Files\Python37\lib\asyncio\subprocess.py", line 202, in create_subprocess_shell
    stderr=stderr, **kwds)
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 1486, in subprocess_shell
    protocol, cmd, True, stdin, stdout, stderr, bufsize, **kwargs)
  File "C:\Program Files\Python37\lib\asyncio\base_events.py", line 444, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError

**Comment by TheDevFromKer** [comment]
Hi, Lpker-2006.
Need change line 80 from:
```python
loop = asyncio.new_event_loop()
```
To:
```python
loop = asyncio.ProactorEventLoop()
asyncio.set_event_loop(loop)
```
Or wait my commit.

**Comment by Lpker-2006** [comment]
> Hi, Lpker-2006.
> Need change line 80 from:
> 
> ```python
> loop = asyncio.new_event_loop()
> ```
> 
> To:
> 
> ```python
> loop = asyncio.ProactorEventLoop()
> asyncio.set_event_loop(loop)
> ```
> 
> Or wait my commit.

actually  it stil doesn't work
the wfreerdp.exe seem cant connect the server on the windows

**Comment by TheDevFromKer** [comment]
You test on valid pair? Please provide more info. Because I don't see any error in tests.
